### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by linuxlite** [linuxlite/lite-updater#1]
**Check for updates** - uses notify-send or some other method to inform the user of the result.
**Enable and Disable Auto-Start** - (same as above)

App works great as of this posting.

**Comment by shaggytwodope** [comment]
The check for updates is already making use of a script to refresh cache.

I'll work on libnotify events tho for everything.

**Comment by linuxlite** [comment]
Cheers :+1:

**Comment by shaggytwodope** [comment]
Added basic notify events with commit 6ceec6e, there is more to be refined and reworded no doubt. But for the time being it's in working order. I think testing existing functionality should take priority before more enhancements are made,

**Comment by shaggytwodope** [comment]
I'm closing this issue, as of commit 97d26d1 notify event is triggered to inform user that cache update was completed.
