### ISSUE TITLE
Have lite-updater jump to updates list in updates-gui if there are updates

### ISSUE THREAD

**Issue by linuxlite** [linuxlite/lite-updater#10]
When it's doing it background check for updates in the tray, if there are updates, can it just jump straight to the list of updates in updates-gui instead of running updates-gui from that start when the lite-updater icon is clicked on?

**Comment by shaggytwodope** [comment]
commit cfad49c merely changes the script run when clicked, this now runs `updates-gui-noprompt` which has no prompt.

you'll need to pull from both lite-software and lite-updater to address this, its ready to be tested tho and works fairly well for me.

**Comment by linuxlite** [comment]
Thanks shaggy. Kind of swamped at work at the moment, will take a look and test. Thank you.

**Comment by shaggytwodope** [comment]
@linuxlite When you get time to test I'd like to create release tag for lite-software as well. Since we are relying on a script there as well (unless you rather it be part of this package?)
