### ISSUE TITLE
Dialog Improvement

### ISSUE THREAD

**Issue by shaggytwodope** [linuxlite/lite-updater#11]
Currently the menu says "update cache", this may not be fitting for all users. May want to consider different wording to make sure it's simple for new comers. I'd like some opinions on what the wording might be (or a PR fixing it).

CC @linuxlite @Misko-2083 @AdrianKoshka

**Comment by Misko-2083** [comment]
@shaggytwodope Hm, considering the target audience, I agree that something simple would better fit.  A few ideas on my mind: "Refresh", "Check", ("Check for Updates" < too long?), and my personal favourites "Energize" and "Breathe new life into" :smile_cat: 
Other items in the menu:
"Install Updates" > "Update"
"Change Sources" > "Sources"
"Refresh" > "Reload"

**Comment by shaggytwodope** [comment]
It may be alot better to word things with simple one word.

So currently:
```
About
Configuration
----------------------
Check for Updates (feels a little long, but its on point)
Sources
Update
----------------------
Reload
Quit
```


Unless @linuxlite @AdrianKoshka are against this at all, or think of a better wording. I'd like @Misko-2083 's choice.

**Comment by linuxlite** [comment]
I like the one simple word approach.

About
Configuration
----------------------
Check for Updates (need something shorter me thinks)
Sources
Update
----------------------
Reload
Quit

**Comment by Misko-2083** [comment]
Random ideas coming:
Configuration > Preferences ?
How about adding a "Help" Menu item which opens a  dialog to explain what things are for?
Also you could ask the community maybe a better idea would come up.

**Comment by shaggytwodope** [comment]
To expand on that, I like preferences over configuration.

However Help.. we may want to consider a entry in the help manual, and simply spawn the link?

**Comment by Misko-2083** [comment]
> However Help.. we may want to consider a entry in the help manual, and simply spawn the link?

:+1:

**Comment by shaggytwodope** [comment]
@linuxlite @AdrianKoshka Could one of you create an entry in the manual for me to point to? Or would we rather keep the help for updater out of the manual?

**Comment by shaggytwodope** [comment]
Here is a screenshot of it currently, http://puu.sh/ogKk5/383329f11c.png

Can check out the branch https://github.com/shaggytwodope/lite-updater/tree/menu_dialog

**Comment by shaggytwodope** [comment]
Decided to change icon for preferences.... cause gtk has a default for it.

http://puu.sh/ogKZ8/74e0364652.png

**Comment by AdrianKoshka** [comment]
I agree with @shaggytwodope and @Misko-2083 on wording, seems alright to me. The addition of a ``help`` menu would be great. Adding page for lite-updater would make sense to me, I'll have to take a look at the manual again to see how stuff is laid out.

**Comment by shaggytwodope** [comment]
If we are ok with the current wording, I can merge and tag new release. `Help` link can be added later should we decide on best way to go.

CC @Misko-2083 @AdrianKoshka @linuxlite

**Comment by AdrianKoshka** [comment]
That'd be fine with me @shaggytwodope.
