### ISSUE TITLE
Add Automatic Updates

### ISSUE THREAD

**Issue by linuxlite** [linuxlite/lite-updater#5]
This is just a thought for now, no need to add this before first release.
Add ability from tray icon or Configuration tool to turn on/off or toggle Automatic Updates.

**Comment by AdrianKoshka** [comment]
I feel automatic updates could cause system instability. This wouldn't be something turned on by default obviously though, a nice thing to have would be when you toggle "auto updates" on a warning dialogue box comes up informing the user of the dangers of automatic updates. I know I'm probably stating the obvious here, but I suppose it's always good for someone to say it.
