### ISSUE TITLE
doesn't start: Permission denied

### ISSUE THREAD

**Issue by Simplenuity** [linuxlite/lite-updater#7]
Linux LIte 2.8, 64 bit
fully updated

Start fails, if I try to start lite-updater as user:

`$ lite-updater
Traceback (most recent call last):
  File "/usr/bin/lite-updater", line 15, in <module>
    import apt
  File "/usr/lib/python2.7/dist-packages/apt/__init__.py", line 34, in <module>
    apt_pkg.init_config()
SystemError: E:Opening configuration file /etc/apt/apt.conf.d/local - ifstream::ifstream (13: Permission denied)
`

**Comment by shaggytwodope** [comment]
Can you run `ls -l /etc/apt/apt.conf.d/` and post the whole output.

**Comment by Simplenuity** [comment]
$ ls -l /etc/apt/apt.conf.d/
total 56
-rw-r--r-- 1 root root   49 Jan 26  2015 00aptitude
-rw-r--r-- 1 root root   40 Jan 26  2015 00trustcdrom
-rw-r--r-- 1 root root  643 Apr 11  2014 01autoremove
-rw-r--r-- 1 root root 1058 Feb 25 22:47 01autoremove-kernels
-rw-r--r-- 1 root root  129 Aug 22  2011 10periodic
-rw-r--r-- 1 root root  108 Aug 22  2011 15update-stamp
-rw-r--r-- 1 root root   85 Aug 22  2011 20archive
-rw-r--r-- 1 root root  123 Apr 11  2014 20changelog
-rw-r--r-- 1 root root  243 Mar 11  2013 20dbus
-rw-r--r-- 1 root root 2331 Apr  3  2014 50unattended-upgrades
-rw-r--r-- 1 root root  182 Feb 24  2014 70debconf
-rw-r--r-- 1 root root   32 Feb 22 10:36 99synaptic
-rw-r--r-- 1 root root  231 Aug 22  2011 99update-notifier
-rw------- 1 root root   61 Jan 30  2015 local

Just tried the updater on my Dev machine and it's running fine. On there the listing is the same as above.

**Comment by shaggytwodope** [comment]
Any idea of what created the "local" file, and can you post its contents?

That aside, running `sudo chmod o+r /etc/apt/apt.conf.d/local` should fix the permissions error.

**Comment by Simplenuity** [comment]
# cat /etc/apt/apt.conf.d/local
Dpkg::Options {
   "--force-confdef";
   "--force-confold";

Ah, I've overlooked the difference. On the dev box this file has global r permission - therefore it worked. No idea what created that file. I just checked, it's also on a third machine. All three upgraded to 2.8 from an earlier 2.x version.
Only on the fourth machine I installed 2.8 directly the file "local" is missing.
Not saying it's related to the installation/ upgrade method though. I just don't know :(

**Comment by shaggytwodope** [comment]
Not sure what creates that, I know it's done manually most cases. If it's working for you please close the issue. Otherwise let me know I'll look into it more.

**Comment by Simplenuity** [comment]
In this case it was not done manually. Very strange...
Well, it's working with the correct permissions.
Thanks for your help!
