### ISSUE TITLE
Update screenshot for linuxlite menu to reflect my changes in the .desktop file

### ISSUE THREAD

**Issue by AdrianKoshka** [linuxlite/lite-updater#9]
Update this:
![linux_lite_menu](http://i.imgur.com/Z305Z8Z.png)

to reflect the changes I have made:
- acf8ec837a68ee7843127b4547ae6b4c9697c722
- 9d9556489eeb5e93a57d7784587bd805604bc983
- 6ce5e702c462ebbfe3abb2961f1cb271beb50e35
- f1d8e145a35ef0943d7addec3cc851e995342fa4
- f29f199116919841ce823f89a4d765f9a892372f

**Comment by shaggytwodope** [comment]
closed with c7c40d1
